#pragma once

#define NEXT_ENEMY_DELAY 1.f
#define NEXT_TIME_ADD_ENEMY 3.f

//#define NEXT_ENEMY_DELAY 0.05f
//#define NEXT_TIME_ADD_ENEMY 1.0f

#define METEOR_MAX_TIME 15.f
#define METEOR_MIN_TIME 10.f

#define BACKGROUND_CLOUDS_COUNT 50
#define CLOUD_VELOCITY 30.f
#define CLOUD_MIN_HEIGHT 0.2f

#define LAND_HEIGHT 0.1f
#define LAND_VELOCITY -500

#define FIGHTER_ACCELERATION_RATE 200.f
#define FIGHTER_MAX_VELOCITY 300.f
#define FIGHTER_STOP_DISTANCE 10.f
#define FIGHTER_BREAK_ACCELERATION_RATE -400.f
#define FIGHTER_ON_PLACE_EPSILON 2.f
#define FIGHTER_NEXT_SHOT_TIME_INTERVAL 0.3f

#define BIRD_X_MAX_VELOCITY -160.f
#define BIRD_X_MIN_VELOCITY -130.f

#define BIRD_Y_VELOCITY 40.f
#define BIRD_MAX_HEIGHT 0.4f
#define BIRD_MIN_HEIGHT 0.15f
#define BIRD_MIN_TIME_CHANGE_DIRECTION 0.5f
#define BIRD_MAX_TIME_CHANGE_DIRECTION 3.0f

#define BOMBER_SLOW_MAX_HEIGHT 0.7f
#define BOMBER_SLOW_MIN_HEIGHT 0.4f
#define BOMBER_SLOW_VELOCITY -70.f

#define BOMBER_FAST_MAX_HEIGHT 1.f
#define BOMBER_FAST_MIN_HEIGHT 0.8f
#define BOMBER_FAST_VELOCITY -200.f

#define INTERCEPTOR_MIN_HEIGHT 0.15f
#define INTERCEPTOR_MAX_HEIGHT 0.9f
#define INTERCEPTOR_VELOCITY -300.f
#define INTERCEPTOR_Y_VELOCITY 200.f

#define INTERCEPTOR_FIRE_RATE 1.5f
#define BULLET_WIDTH 28.f
#define BULLET_HEIGHT 4.f

#define METEOR_X_VELOCITY -100.f
#define METEOR_Y_VELOCITY -100.f

#define ENEMY_BULLET_X_VELOCITY -450.f
#define BULLET_X_VELOCITY 150.f
